version: "3.9"
services:
  app:
    build: ./app
    restart: always
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pizza-drone
      PGUSER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "${PWD}/app/pizza-drone"
